flowchart TD
N1[/"write('Enter your score: ')"/]
N2[/"readln(score)"/]
N3{"if score >= 90"}
N4[/"writeln('Grade: B')"/]
N5[/"writeln('Grade: C')"/]
N6[/"writeln('Grade: D')"/]
N7[/"writeln('Grade: F')"/]
N8(["end"])
N1 --> N2
N2 --> N3
N3 --> N4
N4 --> N5
N5 --> N6
N6 --> N7
N7 --> N8