flowchart TD
N1(["start"])
N2[/"Enter a number: "/]
N3[/"n = input"/]
N4{"n >= 0"}
N5[/"Number is Positive"/]
N6[/"Number is Negative"/]
N7(["end"])
N1 --> N2
N2 --> N3
N3 --> N4
N4 -- Yes --> N5
N4 -- No --> N6
N5 --> N7
N6 --> N7