flowchart TD
  START(["start"])
  N1["let x = prompt('Enter a number:');"]
  N2[x = Number(x)]
  N3{"if x > 0"}
  N4[/"console.log('Positive')"/]
  END(["end"])
  START --> N1
  N1 --> N2
  N2 --> N3
  N3 -->|Yes| N4
  N4 --> END
  N3 -->|No| END