flowchart TD
N1(["start"])
N2["x = expression"]
N3["expression"]
N4{"if x > 5"}
N5[/"x is greater than 5"/]
N6["expression"]
N7{"if x > 15"}
N8[/"x is greater than 15"/]
N9[/"x is not greater than 15"/]
N10[/"End"/]
N11(["end"])
N1 --> N2
N2 --> N3
N3 --> N4
N4 --> N5
N4 --> N6
N6 --> N7
N7 --> N8
N8 --> N9
N7 --> N10
N5 --> N11
N4 -- No --> N11
N8 --> N11
N9 --> N11
N10 --> N11